version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: nginx
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: app
    db:
        image: mysql:latest
        container_name: mysql
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE:-task-hub}"
            MYSQL_USER: "${DB_USERNAME:-user}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-user}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
        volumes:
            - "./_docker/mysql:/var/lib/mysql"
        command:
            - "--default-authentication-plugin=mysql_native_password"




