name: Laravel Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: task-hub
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer Dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, mysql
        coverage: none

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-scripts

    - name: Set up .env
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=task-hub" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Generate key
      run: php artisan key:generate

    - name: Execute migrations
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit

  code-style-fix:
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # для получения полной истории коммитов

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-scripts

    - name: Run Laravel Pint
      run: ./vendor/bin/pint

    - name: Commit and Push code style fixes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Code style fix" -a || true # предотвращает ошибку, если нет изменений
        git push
